{
    "name": "Procurement Purchase Custom",
    "version": "12.0.0.0.0",
    "summary": "Add features to define custom stock rules for purchase \
                procurement.",
    "category": "Warehouse",
    "author": "Comunitea",
    "contributors": ["Rubén Seijas <ruben@comunitea.com>"],
    "website": "http://www.comunitea.com",
    "support": "info@comunitea.com",
    "license": "AGPL-3",
    "price": 0,
    "currency": "EUR",
    "post_load": None,
    "pre_init_hook": None,
    "post_init_hook": None,
    "uninstall_hook": None,
    "auto_install": False,
    "installable": True,
    "application": False,
    "live_test_url": "",
    "demo": [],
    "demo_title": "",
    "demo_addons": [],
    "demo_addons_hidden": [],
    "demo_url": "",
    "demo_summary": "",
    "demo_images": [],
    "external_dependencies": {"python": [], "bin": []},
    "depends": ["stock", "purchase"],
    "data": [
        "views/product_views.xml",
        "views/orderpoint_views.xml",
        "views/purchase_order_views.xml",
        "data/ir_cron.xml"
    ],
    "images": ["/static/description/icon.png"],
    "qweb": [],
}
